### PR TITLE
Rename to setup-beam

### LINKED ISSUE #20: Prepare for rename to setup-beam
After the setup erlang PR is merged (which I'm not linking to as I don't want it to close this issue) we need to do a PR to change instances of `setup-elixir` to `setup-beam`, this should be the limit of the scope.  Once this is merged in, we can rename the repo. 
 
 @wojtekmach had previously tested if checking the name of repo and/or action effects usage of existing releases and it seems no, it should be fine. Though, we should surely double check this and do whatever we can do ensure this is the case prior.  

If all this is good, then we can publish `setup-beam@v1`, once again operating under the assumption that `setup-elixir@v1` will continue to work as is.

### PR DESCRIPTION
**Pull request by starbelly**
This PR touches all files where we had `setup-elixir` but is now renamed to `setup-beam`. 

Edit:

Closes #20

### CODE REVIEW

**Comment by starbelly** [comment]
Let's wait until at least Monday to merge this IMO.

**Review by paulo-ferraz-oliveira — APPROVED** [review]
I'm not sure if the change around the `throw` was made by you or by `format`, but after #9 `format` might change stuff again.

**Review by ericmj — APPROVED** [review]

**Comment by paulo-ferraz-oliveira** [comment]
We're all set, it seems. Shall the games begin? 😄

**Comment by starbelly** [comment]
Yup, might as well.

**Comment by ericmj** [comment]
Thanks @starbelly! 💜

**Pull request merged**
